#!/usr/bin/env python3
"""
sim/island_gapbracket.py — ISLAND-ASDRAWN Pass A': re-grade the island verdict under physical gap
commutation of the LOAD gaps (SG3a1/SG4a1).
=====================================================================================================
Consumer of the Pass A (r0.1) ngspice harness — at this head it lives at
`sim/island_asdrawn_r01_spice.py` (renamed from `sim/island_asdrawn.py` by the r0.2 commit; frozen).
Its deck builder, raw reader and ledger are imported read-only; ONLY the gap elements of the
generated deck are rewritten (as D1 did). New decks: `spice/ia2_*`.

Gap commutation as mode schedules (no ngspice state machine) [ME]:
  every gap = three parallel conductances behind its sense source — bidirectional (V/RON),
  forward rectifier and reverse rectifier (soft rect, RON) — enabled by PWL mode sources.
  bidirectional -> rectifier(sign of the current) inside a same-sign half-cycle is SEAMLESS (both
  conduct I = V/RON there), and the rectifier then extinguishes EXACTLY at its natural current
  zero: extinction is event-exact, never a chop (H2).
  A rule engine reads a run's traces and derives each load gap's schedule for the chosen model
  (M-OW / M-RD / M-SR / D1); the run is repeated until the schedule reproduces itself (fixed point).

Models (brief §2):
  M-OW  one-way (Pass A gap_oneway) — the asymmetric bound (a rectifier).
  M-RD  arc bidirectional from ignition until a half-cycle's current peak < I_hold (fraction h of
        the event's first half-cycle peak); extinction only at a current zero; afterwards the
        established forward rectifier. h -> 0: extinction at the last forward zero before the
        window ends (full ring-down, no chop).
  M-SR  as M-RD, plus a 10 us holdoff after each extinction: re-ignition in EITHER direction if
        |V_gap| > rho(t)|V_f|, rho = 1 - exp(-(t - t_ext)/t_rec) [IR]; afterwards forward rectifier.
  D1    (reproduction only) bidirectional for 300 us after the station, then one-way.
Tiers [OC]/[IR]/[RH]/[ME]. Pure EE firewall.
"""
import csv
import math
import os
import re
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE); sys.path.insert(0, ROOT); sys.path.insert(0, os.path.join(ROOT, "reference"))
import island_asdrawn_r01_spice as a1           # the Pass A record (frozen; read-only use)
import island_resonant_core as irc              # frozen

SPICE, RAW = a1.SPICE, a1.RAW
T, DEG = a1.T_CYC, a1.DEG
EDGE_IGN = a1.EDGE_S                            # Pass A arming / disarm edge (0.5 us)
EDGE_SW = 10e-9                                 # internal mode transitions (<< 0.69 us half-cycle) [ME]
EDGE_D1 = a1.EDGE_S                             # D1's own transition edge
D1_BIDIR = 300e-6
H_TO_ZERO = 1e-4            # I_hold -> 0 realised as 1e-4 of i_pk1. After the first (transfer)
                            # half-cycle the ring CURRENT is only ~1-7 % of i_pk1 while its VOLTAGE
                            # swing is ~V_f, so a 1 % threshold is not a ring-down (measured). If the
                            # threshold is not met inside the window the arc is held to the window
                            # end (residual < 1e-3 i_pk1 there: H2). Causal -> stable fixed point. [ME]
HOLDOFF = 10e-6
T_SPIKE = 50e-9             # i_pk1 = the RING's first half-cycle peak: the first 50 ns after an
                            # ignition carry the stray-capacitance dump spike (~10 ns, up to ~14x the
                            # ring peak) and are excluded from the holding-current reference [IR]
R_COIL = 40.0                                   # sim/s8_unified_coupled.py                 [OC]
LOAD = a1.LOAD_GAPS
GAPS = tuple(a1.WINDOWS)


# ======================================================================================
# 1. DECK: Pass A deck with the gap elements rewritten to mode-scheduled conductances
# ======================================================================================
def write_gap_sub():
    txt = f"""* ia2_gap.sub — mode-scheduled gap (ISLAND-ASDRAWN Pass A'; generated by sim/island_gapbracket.py)
* bi/f/r = PWL mode sources (0..1): bidirectional arc, forward rectifier, reverse rectifier.
* Same RON / VE / ROFF as Pass A's sparkgap_bidir / gap_oneway (a1.GAP_RON, a1.VE_RECT, a1.GAP_ROFF).
.subckt ia2_gap a b bi f r PARAMS: RON={a1.GAP_RON} ROFF={a1.GAP_ROFF:.0e} VE={a1.VE_RECT}
  Bg a b I='V(bi)*V(a,b)/RON + V(f)/RON*0.5*(V(a,b)+sqrt(V(a,b)*V(a,b)+VE*VE)) + V(r)/RON*0.5*(V(a,b)-sqrt(V(a,b)*V(a,b)+VE*VE)) + V(a,b)/ROFF'
.ends ia2_gap
"""
    open(os.path.join(SPICE, "ia2_gap.sub"), "w").write(txt)


def seg_pwl(segs, ncyc):
    """Mode segments [(t0, t1, mode, edge_in)] -> three PWL strings (bi, f, r). A segment's mode
    ramps in over edge_in starting at t0; the last segment of a window ramps out over EDGE_IGN at
    its t1 unless the next segment starts there."""
    out = {}
    for m in ("bi", "f", "r"):
        pts = [(0.0, 0.0)]
        cur = 0.0
        segs_s = sorted(segs, key=lambda x: x[0])
        for k, (t0, t1, mode, ein) in enumerate(segs_s):
            val = 1.0 if mode == m else 0.0
            if val != cur:
                pts.append((t0, cur)); pts.append((t0 + ein, val)); cur = val
            nxt = segs_s[k + 1][0] if k + 1 < len(segs_s) else None
            if nxt is None or nxt > t1 + 1e-12:
                if cur != 0.0:
                    pts.append((t1, cur)); pts.append((t1 + EDGE_IGN, 0.0)); cur = 0.0
        pts.append((ncyc * T + 1e-3, cur))
        # times rounded exactly as Pass A's PWLs ({:.9e}): coincident stations must produce the
        # SAME breakpoint, else ngspice is forced through a 1e-14 s step mid-dump [ME]
        clean = []
        for tt, vv in pts:
            tt = float(f"{tt:.9e}")
            if clean and tt <= clean[-1][0]:
                tt = float(f"{clean[-1][0] + 1e-12:.9e}")
            clean.append((tt, vv))
        body = " ".join(f"{tt:.9e} {vv:g}" for tt, vv in clean)
        chunks = body.split(" ")
        lines = [" ".join(chunks[i:i + 16]) for i in range(0, len(chunks), 16)]
        out[m] = "PWL(" + "\n+ ".join(lines) + ")"
    return out


def build(cfg, sched, motor_r=True):
    """Pass A deck for cfg (a1.build, untouched) with gap lines rewritten per `sched`
    {gap: segments} and (motor in) R_COIL in series with each motor coil."""
    deck, meta = a1.build(cfg)
    L = deck.splitlines()
    out = []
    for ln in L:
        m = re.match(r"^X(\w+) (s_\w+) (\S+) arm_\w+ (sparkgap_bidir|gap_oneway)$", ln)
        if m and m.group(1) in GAPS:
            g = m.group(1)
            out.append(f"X{g} {m.group(2)} {m.group(3)} mbi_{g.lower()} mf_{g.lower()} mr_{g.lower()} ia2_gap")
            pw = seg_pwl(sched[g], cfg.ncyc)
            for mm in ("bi", "f", "r"):
                out.append(f"V_m{mm}_{g.lower()} m{mm}_{g.lower()} 0 {pw[mm]}")
            continue
        m = re.match(r"^L_(L_[AB]\d) (\S+) (\S+) (\S+)$", ln)
        if m and motor_r and cfg.motor:
            nm, a, b, Lv = m.groups()
            out.append(f"L_{nm} {a} x_{nm.lower()} {Lv}")
            out.append(f"R_{nm}coil x_{nm.lower()} {b} {R_COIL:g}")
            continue
        if ln.startswith(".include sparkgap_bidir.sub"):
            out.append(ln); out.append(".include ia2_gap.sub"); continue
        out.append(ln)
    meta = dict(meta)
    if cfg.motor and motor_r:
        meta["motor_r"] = [(nm, R_COIL) for nm, a, b, Lv in meta["inds"] if nm.startswith("L_")]
    return "\n".join(out) + "\n", meta


def run(cfg, sched, motor_r=True):
    write_gap_sub()
    deck, meta = build(cfg, sched, motor_r)
    open(os.path.join(SPICE, f"{cfg.name}.cir"), "w").write(deck)
    r = subprocess.run(["ngspice", "-b", f"{cfg.name}.cir"], capture_output=True, text=True,
                       cwd=SPICE, timeout=7200)
    log = r.stdout + r.stderr
    ok = ("too small" not in log) and ("aborted" not in log.lower())
    d = a1.read_raw(os.path.join(RAW, f"{cfg.name}.raw"))
    return dict(cfg=cfg, meta=meta, d=d, ok=ok, sched=sched)


# ======================================================================================
# 2. SCHEDULES / RULE ENGINE
# ======================================================================================
BKPT_OFFSET = 2e-9          # station edges offset 2 ns: never coincident (to ~1e-12) with the
                            # periodic Cx/clock PWL breakpoints ngspice computes itself [ME]


def windows_abs(g, ncyc):
    a, b = a1.WINDOWS[g]
    return [(c * T + a * DEG + BKPT_OFFSET, c * T + b * DEG + BKPT_OFFSET) for c in range(ncyc)]


def base_mode(g, bracket):
    if g in a1.RAIL_GAPS:
        return "f"
    if g in a1.ISLAND_GAPS:
        return "bi" if bracket == "a" else "f"
    return "f"                                      # load: Pass A one-way


def sched_static(cfg, load_mode="f", d1=None):
    """Static schedules: every gap its Pass A mode; load gaps `load_mode` over the window.
    d1: None | 'load' | 'all' -> D1's rule (bidir 300 us after station, then one-way)."""
    s = {}
    for g in GAPS:
        segs = []
        for (t0, t1) in windows_abs(g, cfg.ncyc):
            mode = load_mode if g in LOAD else base_mode(g, cfg.bracket)
            if d1 == "all" or (d1 == "load" and g in LOAD):
                segs += [(t0, t0 + D1_BIDIR, "bi", EDGE_IGN), (t0 + D1_BIDIR, t1, "f", EDGE_D1)]
            else:
                segs.append((t0, t1, mode, EDGE_IGN))
        s[g] = segs
    return s


def _zeros(t, i, t0, t1, eps):
    """Sign-change instants of i on (t0, t1] ignoring |i| < eps (linear interpolation)."""
    k0, k1 = np.searchsorted(t, t0), np.searchsorted(t, t1)
    tt, ii = t[k0:k1], i[k0:k1]
    s = np.sign(np.where(np.abs(ii) < eps, 0.0, ii))
    zs = []
    last = 0.0; lastk = None
    for k in range(len(ii)):
        if s[k] == 0:
            continue
        if last != 0 and s[k] != last:
            j = lastk
            # interpolate between the last nonzero-signed sample and this one
            ta, tb, ia, ib = tt[j], tt[k], ii[j], ii[k]
            zs.append(ta + (tb - ta) * ia / (ia - ib))
        last = s[k]; lastk = k
    return zs


def derive_event(t, i, v, t_ign, t_end, model, h, t_rec, holdoff, rec):
    """Derive the segment list for one load gap from t_ign to t_end from traces (t, i, v).
    Returns segs and appends event records to rec."""
    segs = []
    Vf = float(np.interp(t_ign, t, v))
    ein = EDGE_IGN if not rec else EDGE_SW
    imax = float(np.max(np.abs(i[np.searchsorted(t, t_ign):np.searchsorted(t, t_end)]))) \
        if np.searchsorted(t, t_end) > np.searchsorted(t, t_ign) else 0.0
    zs = [z for z in _zeros(t, i, t_ign, t_end, 1e-9 * max(imax, 1e-300)) if z < t_end]
    bounds = [t_ign] + zs
    half = []
    for k in range(len(zs)):
        a, b = bounds[k], bounds[k + 1]
        if k == 0:
            a = min(a + T_SPIKE, b)                          # ring peak, not the stray-dump spike
        ka, kb = np.searchsorted(t, a), max(np.searchsorted(t, b), np.searchsorted(t, a) + 1)
        seg = i[ka:kb]
        kp = int(np.argmax(np.abs(seg))) if len(seg) else 0
        half.append(dict(a=a, b=b, pk=float(abs(seg[kp])) if len(seg) else 0.0,
                         sgn=float(np.sign(seg[kp])) if len(seg) else 0.0,
                         tpk=float(t[ka + kp]) if len(seg) else a))
    ev = dict(t_ign=t_ign, Vf=Vf, n_half=len(half), p1=half[0]["pk"] if half else imax,
              p1_full=imax if not zs else float(np.max(np.abs(i[np.searchsorted(t, t_ign):np.searchsorted(t, zs[0])]))))
    rec.append(ev)
    if not half:                                             # no ring (G twins): arc held
        segs.append((t_ign, t_end, "bi", ein)); ev["ext"] = None
        i_end = float(np.interp(t_end, t, i)); ref = max(ev.get("p1_full") or 0.0, imax, 1e-300)
        if abs(i_end) > 1e-3 * ref:                          # window closes on current: next zero
            zs2 = _zeros(t, i, t_end, min(t_end + 2e-3, t[-1]), 1e-12 * max(abs(i_end), 1e-300))
            t_z = zs2[0] if zs2 else min(t_end + 2e-3, t[-1])
            segs.append((t_end, t_z + EDGE_SW, "f" if i_end > 0 else "r", EDGE_SW))
            ev["closing_zero"] = t_z; ev["i_at_end"] = 0.0
        else:
            ev["i_at_end"] = abs(i_end)
        return segs
    p1 = half[0]["pk"]
    # choose the extinguishing half-cycle
    kx = None
    if h is not None and h <= 0:
        h = H_TO_ZERO
    if h is not None and h > 0:
        for k, hc in enumerate(half):
            if hc["pk"] < h * p1:
                kx = k; break
    if kx is None:                                           # not met in the window: arc held
        segs.append((t_ign, t_end, "bi", ein)); ev["ext"] = None
        # the electrodes part at t_end: the arc goes out at its NEXT natural current zero
        # (rectifier of the current's sign from t_end), never by a chop (H2)
        i_end = float(np.interp(t_end, t, i))
        if abs(i_end) > 1e-3 * max(ev.get("p1_full") or 0.0, ev["p1"] or 0.0, 1e-300):
            zs2 = _zeros(t, i, t_end, min(t_end + 2e-3, t[-1]), 1e-12 * max(abs(i_end), 1e-300))
            t_z = zs2[0] if zs2 else min(t_end + 2e-3, t[-1])
            segs.append((t_end, t_z + EDGE_SW, "f" if i_end > 0 else "r", EDGE_SW))
            ev["closing_zero"] = t_z
        ev["i_at_end"] = 0.0 if abs(i_end) > 1e-3 * max(ev.get("p1_full") or 0.0, ev["p1"] or 0.0, 1e-300) \
            else abs(i_end)
        return segs
    hc = half[kx]
    mode_x = "f" if hc["sgn"] > 0 else "r"
    segs.append((t_ign, hc["tpk"], "bi", ein))
    segs.append((hc["tpk"], hc["b"], mode_x, EDGE_SW))
    t_ext = hc["b"]
    ev.update(ext=t_ext, k_ext=kx, sgn_ext=hc["sgn"], i_at_ext=float(abs(np.interp(t_ext, t, i))))
    if model == "RD" or holdoff <= 0:
        # afterwards: the established forward rectifier
        if mode_x == "f":
            segs[-1] = (hc["tpk"], t_end, "f", EDGE_SW)
        else:
            segs.append((t_ext, t_end, "f", EDGE_SW))
        return segs
    # M-SR holdoff: off, re-ignite in either direction if |v| > rho |Vf|
    t_h1 = min(t_ext + holdoff, t_end)
    k0, k1 = np.searchsorted(t, t_ext), np.searchsorted(t, t_h1)
    tt, vv = t[k0:k1], v[k0:k1]
    rho = np.ones_like(tt) if t_rec <= 0 else 1.0 - np.exp(-(tt - t_ext) / t_rec)
    hit = np.where(np.abs(vv) > rho * abs(Vf))[0]
    # ignore the first 20 ns (the zero itself / the 10 ns mode edge)
    hit = [k for k in hit if tt[k] > t_ext + 2 * EDGE_SW]
    if hit:
        t_r = float(tt[hit[0]])
        segs.append((t_ext, t_r, "off", EDGE_SW))
        ev["reignite"] = t_r
        segs += derive_event(t, i, v, t_r, t_end, model, h, t_rec, holdoff, rec)
        return segs
    segs.append((t_ext, t_h1, "off", EDGE_SW))
    if t_h1 < t_end:
        segs.append((t_h1, t_end, "f", EDGE_SW))
    ev["reignite"] = None
    return segs


def derive_sched(res, cfg, model, h=None, t_rec=0.0, holdoff=HOLDOFF, bracket=None):
    """Full schedule for all gaps from the traces of `res` under the load-gap model."""
    d = res["d"]; t = d["time"]
    s = sched_static(cfg)
    events = {}
    for g in LOAD:
        a, b = _gap_nodes(g)
        i = d[f"i(v_s{g.lower()})"]
        v = (d[f"v({a})"] if a != "0" else 0 * t) - (d[f"v({b})"] if b != "0" else 0 * t)
        segs = []; rec = []
        for (t0, t1) in windows_abs(g, cfg.ncyc):
            if t0 > t[-1]:
                break
            segs += derive_event(t, i, v, t0, min(t1, t[-1]), model, h, t_rec, holdoff, rec)
        s[g] = segs
        events[g] = rec
    return s, events


def _gap_nodes(g):
    for comp, a, b in a1.edge_list():
        if comp == g:
            return a1._n(a, "collapsed"), a1._n(b, "collapsed")
    raise KeyError(g)


def _norm(s):
    return {g: sorted((round(a / 1e-9), round(b / 1e-9), m) for a, b, m, e in segs if m != "off")
            for g, segs in s.items()}


def fixed_point(cfg, model, h=None, t_rec=0.0, holdoff=HOLDOFF, maxit=10, tol_ns=30):
    """Iterate run -> derive -> run until the derived load-gap schedule reproduces itself."""
    if model in ("OW",):
        r = run(cfg, sched_static(cfg, "f")); r["iters"] = 1; r["events"] = {}
        return r
    sched = sched_static(cfg, "bi")                          # start: arc held all window
    hist = []
    for it in range(maxit):
        cfg.name = re.sub(r"_it\d+$", "", cfg.name) + f"_it{it}"
        r = run(cfg, sched)
        new, ev = derive_sched(r, cfg, model, h, t_rec, holdoff)
        same = _close(new, sched, tol_ns)
        hist.append(same)
        if same:
            r["iters"] = it + 1; r["events"] = ev; r["converged"] = True
            return r
        sched = new
        _rm_raw(cfg.name)                          # intermediate iteration trace no longer needed
    r["iters"] = maxit; r["events"] = ev; r["converged"] = False
    return r


def _rm_raw(name):
    p = os.path.join(RAW, f"{name}.raw")
    if os.path.exists(p):
        os.remove(p)


def _close(s1, s2, tol_ns):
    for g in LOAD:
        a = sorted(s1[g]); b = sorted(s2[g])
        if len(a) != len(b):
            return False
        for x, y in zip(a, b):
            if x[2] != y[2] or abs(x[0] - y[0]) > tol_ns * 1e-9 or abs(x[1] - y[1]) > tol_ns * 1e-9:
                return False
    return True


# ======================================================================================
# 3. OBSERVABLES — ledger (conservation) and TRV / event peak record, kept separate
# ======================================================================================
LEDGER_CYCLES = a1.LEDGER_CYCLES


def ledger(res, cyc):
    """Pass A ledger (frozen a1.ledger) + motor coil R dissipation. Returns the a1 dict plus the
    signed residual s = (W - dE - E_diss)/E_diss and the +5 % total-dissipation trip."""
    L = a1.ledger(res, cyc)
    d = res["d"]; t = d["time"]; sl = a1._seg(t, cyc * T, (cyc + 1) * T)
    e_m = 0.0
    for nm, R in res["meta"].get("motor_r", []):
        e_m += R * a1._trap(d[f"i(l_{nm.lower()})"][sl] ** 2, t[sl])
    L["diss"]["motor_R"] = e_m
    Ed = L["E_diss"] + e_m
    s = (L["W"] - L["dE"] - Ed) / Ed
    s5 = (L["W"] - L["dE"] - 1.05 * Ed) / Ed
    Eg = L["E_gap"]
    return dict(W=L["W"], dE=L["dE"], E_diss=Ed, E_gap=Eg, diss=L["diss"], eta=L["dE"] / L["W"],
                resid=abs(s), resid_gap=abs(L["W"] - L["dE"] - Ed) / Eg, signed=s, trip_shift=s5 - s)


def summarize(res):
    d = res["d"]; t = d["time"]; c = res["cfg"]
    ncomp = int(t[-1] / T + 1e-9)
    cyc = [k for k in LEDGER_CYCLES if k + 1 <= ncomp]
    if not cyc:
        raise RuntimeError(f"{c.name}: ngspice stopped after {t[-1] / T:.2f} cycles (clean={res.get('ok')})")
    leds = [ledger(res, k) for k in cyc]
    W = [L["W"] for L in leds]
    out = dict(name=c.name, lx=c.lx, bracket=c.bracket, stray=c.stray_ref, motor=c.motor,
               reltol=c.reltol, cycles=ncomp, clean=res.get("ok"), iters=res.get("iters"),
               converged=res.get("converged", True),
               z=a1.z_of(t, d["v(1)"], d["v(4)"]), eta=float(np.mean([L["eta"] for L in leds])),
               resid=max(L["resid"] for L in leds), resid_gap=max(L["resid_gap"] for L in leds),
               trip_shift=float(np.mean([L["trip_shift"] for L in leds])),
               T_load=float(np.mean([(L["diss"].get("SG3a1", 0) + L["diss"].get("SG4a1", 0)) / L["W"] for L in leds])),
               T_esr=float(np.mean([sum(v for k, v in L["diss"].items() if k.endswith("esr")) / L["W"] for L in leds])),
               T_motor=float(np.mean([L["diss"].get("motor_R", 0) / L["W"] for L in leds])))
    res["leds"] = leds
    return out


def trv_record(res, cyc_list=(8, 9, 10)):
    """H4: per load event, reverse peak |V_gap| after extinction / |V_f| and its delay."""
    d = res["d"]; t = d["time"]; rows = []
    for g in LOAD:
        a, b = _gap_nodes(g)
        i = d[f"i(v_s{g.lower()})"]
        v = (d[f"v({a})"] if a != "0" else 0 * t) - (d[f"v({b})"] if b != "0" else 0 * t)
        for c in cyc_list:
            t0, t1 = windows_abs(g, c + 1)[c]
            if t1 > t[-1]:
                continue
            evs = (res.get("events") or {}).get(g)
            ext = None
            if evs:
                cand = [e for e in evs if t0 - 1e-12 <= e["t_ign"] <= t1 and e.get("ext")]
                ext = cand[-1]["ext"] if cand else None
                Vf = cand[-1]["Vf"] if cand else float(np.interp(t0, t, v))
                p1 = cand[-1]["p1"] if cand else None
            if ext is None:                                   # M-OW: first current zero
                k0, k1 = np.searchsorted(t, t0), np.searchsorted(t, t1)
                ii = i[k0:k1]; kp = int(np.argmax(np.abs(ii))); p1 = float(abs(ii[kp]))
                zz = np.where(np.abs(ii[kp:]) < 1e-3 * p1)[0]
                if not len(zz):
                    continue
                ext = float(t[k0 + kp + zz[0]]); Vf = float(np.interp(t0, t, v))
            k0, k1 = np.searchsorted(t, ext), np.searchsorted(t, ext + 3e-6)
            kr = k0 + int(np.argmax(np.abs(v[k0:k1])))
            rows.append(dict(gap=g, cycle=c, Vf=Vf, t_ext_us=(ext - t0) * 1e6,
                             i_ext_over_p1=float(abs(np.interp(ext, t, i)) / p1) if p1 else None,
                             trv_ratio=float(v[kr] / Vf), trv_delay_us=float((t[kr] - ext) * 1e6)))
    return rows


def _selftest():
    ok = True
    # a seamless bi->f hand-off: PWL values sum to 1 through the edge
    segs = [(1e-6, 2e-6, "bi", EDGE_IGN), (2e-6, 3e-6, "f", EDGE_SW)]
    pw = seg_pwl(segs, 1)
    def val(s, tt):
        body = s.replace("PWL(", " ").replace(")", " ").replace("\n+ ", " ")
        nums = [float(x) for x in body.split()]
        ts, vs = nums[0::2], nums[1::2]
        return float(np.interp(tt, ts, vs))
    for tt in (2.0e-6, 2.005e-6, 2.01e-6):
        ok &= abs(val(pw["bi"], tt) + val(pw["f"], tt) - 1.0) < 1e-9
    # zero finder on a damped sine
    tt = np.linspace(0, 10e-6, 20001); ii = np.exp(-tt / 20e-6) * np.sin(2 * np.pi * tt / 1.38e-6)
    zs = _zeros(tt, ii, 1e-9, 5e-6, 1e-12)
    ok &= abs(zs[0] - 0.69e-6) < 2e-9
    ok &= set(GAPS) == set(a1.WINDOWS) and set(LOAD) <= set(GAPS)
    if not ok:
        raise AssertionError("island_gapbracket on-load self-test FAILED")
    return ok


SELFTEST_OK = _selftest()


# ======================================================================================
# 4. H5 — independent event engine: Python linear network at frozen capacitances
# ======================================================================================
def _pwl_points(segs, ncyc, m):
    s = seg_pwl(segs, ncyc)[m]
    body = s.replace("PWL(", " ").replace(")", " ").replace("\n+ ", " ")
    nums = [float(x) for x in body.split()]
    return np.array(nums[0::2]), np.array(nums[1::2])


def event_engine(res, g, t_ign, span=3e-6):
    """Integrate the frozen-C network from the ngspice pre-state at t_ign with scipy Radau.
    Gap conductances follow the SAME mode schedule. Returns t, V (nodes), I_L, i_gap(g)."""
    from scipy.integrate import solve_ivp
    d, m, cfg = res["d"], res["meta"], res["cfg"]
    nodes = m["nodes"]; ix = {n: k for k, n in enumerate(nodes)}; N = len(nodes)
    K = np.zeros((N, N))

    def addc(a, b, C):
        ia = ix.get(a); ib = ix.get(b)
        if ia is not None: K[ia, ia] += C
        if ib is not None: K[ib, ib] += C
        if ia is not None and ib is not None:
            K[ia, ib] -= C; K[ib, ia] -= C
    for nm, a, b, C in m["caps"]:
        addc(a, b, C)
    for nm, a, b, kind in m["varcaps"]:
        addc(a, b, float(a1._c_of_t(kind, np.array([t_ign]))[0]))
    Ki = np.linalg.inv(K)
    t = d["time"]
    V0 = np.array([np.interp(t_ign, t, d[f"v({n})"]) for n in nodes])
    inds = [x for x in m["inds"] if x[3] > 0]
    Rm = dict(m.get("motor_r", []))
    Rs = []
    for nm, a, b, Lv in inds:
        Rs.append(cfg.rlx if nm in ("Lx3", "Lx4") and cfg.rlx > 0 else Rm.get(nm, 0.0))
    I0 = np.array([np.interp(t_ign, t, d[f"i(l_{nm.lower()})"]) for nm, a, b, Lv in inds])
    Lv_ = np.array([x[3] for x in inds]); Rs = np.array(Rs)
    gaps = m["gaps"]
    modes = {}
    for gg, a, b in gaps:
        modes[gg] = {mm: _pwl_points(res["sched"][gg], cfg.ncyc, mm) for mm in ("bi", "f", "r")}
    RON, ROFF, VE = a1.GAP_RON, a1.GAP_ROFF, a1.VE_RECT

    def vab(V, a, b):
        return (V[ix[a]] if a in ix else 0.0) - (V[ix[b]] if b in ix else 0.0)

    def gap_i(gg, a, b, V, tt):
        x = vab(V, a, b); md = modes[gg]
        bi = np.interp(tt, *md["bi"]); f = np.interp(tt, *md["f"]); r = np.interp(tt, *md["r"])
        s = math.sqrt(x * x + VE * VE)
        return bi * x / RON + f / RON * 0.5 * (x + s) + r / RON * 0.5 * (x - s) + x / ROFF

    def rhs(tt, y):
        V = y[:N]; I = y[N:]
        inj = np.zeros(N)
        for gg, a, b in gaps:
            ig = gap_i(gg, a, b, V, tt)
            if a in ix: inj[ix[a]] -= ig
            if b in ix: inj[ix[b]] += ig
        dI = np.zeros(len(inds))
        for k, (nm, a, b, Lx) in enumerate(inds):
            if a in ix: inj[ix[a]] -= I[k]
            if b in ix: inj[ix[b]] += I[k]
            dI[k] = (vab(V, a, b) - Rs[k] * I[k]) / Lx
        return np.concatenate([Ki @ inj, dI])
    sol = solve_ivp(rhs, (t_ign, t_ign + span), np.concatenate([V0, I0]), method="Radau",
                    rtol=1e-9, atol=1e-12 * max(1.0, float(np.max(np.abs(V0)))), dense_output=True,
                    max_step=2e-9)
    tt = sol.t; Y = sol.y
    a, b = _gap_nodes(g)
    ig = np.array([gap_i(g, a, b, Y[:N, k], tt[k]) for k in range(len(tt))])
    return dict(t=tt, V=Y[:N], I=Y[N:], ig=ig, nodes=nodes, ix=ix, K=K, inds=inds, Rs=Rs,
                gaps=gaps, gap_i=gap_i)


def event_metrics_engine(E, g, t_ign):
    t, ig = E["t"], E["ig"]; a, b = _gap_nodes(g); ix = E["ix"]
    v = (E["V"][ix[a]] if a in ix else 0) - (E["V"][ix[b]] if b in ix else 0)
    return _event_metrics(t, ig, v, t_ign, E=E)


def event_metrics_spice(res, g, t_ign, span=3e-6):
    d = res["d"]; t = d["time"]; k0, k1 = np.searchsorted(t, t_ign), np.searchsorted(t, t_ign + span)
    a, b = _gap_nodes(g)
    v = (d[f"v({a})"] if a != "0" else 0 * t) - (d[f"v({b})"] if b != "0" else 0 * t)
    return _event_metrics(t[k0:k1], d[f"i(v_s{g.lower()})"][k0:k1], v[k0:k1], t_ign, res=res,
                          sl=(k0, k1))


def _event_metrics(t, ig, v, t_ign, E=None, res=None, sl=None):
    """t1/2 (ignition -> first current zero), TRV ratio (reverse peak / V_f), node-3 cap charge
    partition over [t_ign, zero], gap + ESR dissipation over the span."""
    Vf = float(v[0]); kp = int(np.argmax(np.abs(ig))); p1 = float(abs(ig[kp]))
    zz = [k for k in range(kp, len(ig) - 1) if ig[k] * ig[k + 1] <= 0]
    if not zz:
        return None
    k = zz[0]; tz = t[k] + (t[k + 1] - t[k]) * ig[k] / (ig[k] - ig[k + 1])
    kz = k
    kr = kz + int(np.argmax(np.abs(v[kz:])))
    out = dict(t_half_us=(tz - t_ign) * 1e6, trv_ratio=float(v[kr] / Vf), i_pk=p1, Vf=Vf)
    # node-3 partner charges (caps attached to node 3) at the zero
    if E is not None:
        V = E["V"]; ix = E["ix"]; K = E["K"]
        dq = K @ (np.array([np.interp(tz, t, V[j]) for j in range(len(ix))]) - V[:, 0])
        out["dq3"] = float(dq[ix["3"]])
        # dissipation: gaps + series R over the span
        pg = np.zeros(len(t))
        for gg, a, b in E["gaps"]:
            x = np.array([(V[ix[a], j] if a in ix else 0) - (V[ix[b], j] if b in ix else 0) for j in range(len(t))])
            ii = np.array([E["gap_i"](gg, a, b, V[:, j], t[j]) for j in range(len(t))])
            pg += x * ii
        pr = np.sum(E["Rs"][:, None] * E["I"] ** 2, axis=0)
        out["E_diss"] = float(np.trapezoid(pg + pr, t))
    if res is not None:
        d = res["d"]; m = res["meta"]; k0, k1 = sl; tt = d["time"][k0:k1]
        nodes = m["nodes"]
        V = np.array([d[f"v({n})"][k0:k1] for n in nodes])
        ix = {n: j for j, n in enumerate(nodes)}; N = len(nodes)
        K = np.zeros((N, N))
        for nm, a, b, C in m["caps"]:
            ia, ib = ix.get(a), ix.get(b)
            if ia is not None: K[ia, ia] += C
            if ib is not None: K[ib, ib] += C
            if ia is not None and ib is not None: K[ia, ib] -= C; K[ib, ia] -= C
        for nm, a, b, kind in m["varcaps"]:
            C = float(a1._c_of_t(kind, np.array([t_ign]))[0]); ia, ib = ix.get(a), ix.get(b)
            if ia is not None: K[ia, ia] += C
            if ib is not None: K[ib, ib] += C
            if ia is not None and ib is not None: K[ia, ib] -= C; K[ib, ia] -= C
        dq = K @ (np.array([np.interp(tz, tt, V[j]) for j in range(N)]) - V[:, 0])
        out["dq3"] = float(dq[ix["3"]])
        pg = np.zeros(len(tt))
        for gg, a, b in m["gaps"]:
            x = (d[f"v({a})"][k0:k1] if a != "0" else 0) - (d[f"v({b})"][k0:k1] if b != "0" else 0)
            pg += x * d[f"i(v_s{gg.lower()})"][k0:k1]
        pr = np.zeros(len(tt))
        for nm, a, b, Lv in m["inds"]:
            if nm in ("Lx3", "Lx4") and Lv > 0 and res["cfg"].rlx > 0:
                pr += res["cfg"].rlx * d[f"i(l_{nm.lower()})"][k0:k1] ** 2
        for nm, R in m.get("motor_r", []):
            pr += R * d[f"i(l_{nm.lower()})"][k0:k1] ** 2
        out["E_diss"] = float(np.trapezoid(pg + pr, tt))
    return out


def h5_events(res, g="SG3a1", cycles=(8, 9, 10), span=3e-6):
    """H5: >= 3 load events: engine vs ngspice within 1 % on t1/2, dq3, E_diss, TRV ratio."""
    rows = []
    for c in cycles:
        t_ign = windows_abs(g, c + 1)[c][0]
        E = event_engine(res, g, t_ign, span)
        me = event_metrics_engine(E, g, t_ign); ms = event_metrics_spice(res, g, t_ign, span)
        if me is None or ms is None:
            rows.append(dict(cycle=c, ok=False)); continue
        rel = {k: abs(me[k] - ms[k]) / max(abs(ms[k]), 1e-300) for k in ("t_half_us", "dq3", "E_diss", "trv_ratio")}
        rows.append(dict(cycle=c, engine=me, spice=ms, rel=rel, ok=all(v <= 0.01 for v in rel.values())))
    return all(r["ok"] for r in rows), rows


# ======================================================================================
# 5. CAMPAIGN (brief §4) — jobs, cache, verdict
# ======================================================================================
CACHE = os.path.join(HERE, ".ia2_campaign.json")
T_RECS = (0.0, 0.1e-6, 1e-6, 10e-6)
HOLDS = (0.1, 0.3, 0.5, 0.7)
PARITY = (0.9, 1.0, 1.1)
RD_GRID = (0.0, 0.1, 0.3, 0.5, 0.7)


def cfg_of(twin, stray=a1.STRAY_REF_PRIMARY, motor=False, reltol=None, bracket="a"):
    lx = a1.LX_DRAWN if twin in ("R1", "R2") else 0.0
    cx = "big" if twin == "G0" else "profile"
    kw = dict(lx=lx, cx=cx, bracket=bracket, stray_ref=stray, motor=motor)
    if reltol:
        kw["reltol"] = reltol
    return a1.base("ia2_tmp", **kw)


KEEP_RAW = set()


def job_key(twin, model, h=None, t_rec=None, stray=5.0, motor=False, reltol=None, bracket="a"):
    return f"{twin}|{model}|h={h}|trec={t_rec}|s={stray}|m={int(motor)}|rt={reltol}|br={bracket}"


def run_job(key):
    import traceback
    try:
        return _run_job(key)
    except Exception:
        return key, dict(key=key, error=traceback.format_exc()[-1500:], z=float("nan"),
                         eta=float("nan"), iters=None, converged=False, n_reignite=0, h2_max_iext=float("nan"))


def _run_job(key):
    twin, model, h, trec, st, mo, rt, br = [x.split("=")[-1] for x in key.split("|")]
    h = None if h == "None" else float(h); trec = None if trec == "None" else float(trec)
    rt = None if rt == "None" else float(rt)
    c = cfg_of(twin, float(st), bool(int(mo)), rt, br)
    tag = re.sub(r"[^A-Za-z0-9]+", "_", key)[:80]
    c.name = "ia2_" + tag
    if model == "OW":
        r = fixed_point(c, "OW")
    elif model == "SR" and c.lx > 0:
        r = fixed_point_sr(c, "SR", h, trec or 0.0, HOLDOFF)     # chain engine per event
    elif model == "RD" and c.lx > 0 and h and h > 0:
        r = fixed_point_sr(c, "RD", h, 0.0, 0.0)                 # same engine, no holdoff
    else:
        r = fixed_point(c, model, h=h, t_rec=trec or 0.0, holdoff=HOLDOFF if model == "SR" else 0.0)
    s = summarize(r)
    s["key"] = key; s["model"] = model; s["h"] = h; s["t_rec"] = trec; s["twin"] = twin
    evs = r.get("events", {})
    # H2 reference = the event's FULL first half-cycle peak (brief), p1_full; the I_hold reference
    # is the ring peak p1 (stray-dump spike excluded, T_SPIKE)
    s["h2_max_iext"] = max([max(e.get("i_at_ext") or 0.0, e.get("i_at_end") or 0.0) /
                            (e.get("p1_full") or e["p1"]) for g in evs for e in evs[g] if e.get("p1")] or [0.0])
    s["n_reignite"] = sum(1 for g in evs for e in evs[g] if e.get("reignite"))
    s["n_events"] = sum(len(evs[g]) for g in evs)
    try:
        s["trv"] = trv_record(r)
    except Exception as e:                               # the record must never block a run
        s["trv"] = str(e)
    if key not in KEEP_RAW:
        _rm_raw(r["cfg"].name)                           # disk: keep only the key traces
    return key, s


def campaign(keys, procs=4):
    import json
    from concurrent.futures import ThreadPoolExecutor
    cache = json.load(open(CACHE)) if os.path.exists(CACHE) else {}
    todo = [k for k in keys if k not in cache]
    with ThreadPoolExecutor(procs) as ex:
        for key, s in ex.map(run_job, todo):
            cache[key] = s
            json.dump(cache, open(CACHE, "w"), default=str, indent=1)
            print(f"{key}: z {s['z']:.4f} eta {s['eta']:.4f} it {s['iters']} conv {s['converged']} "
                  f"reign {s['n_reignite']} h2 {s['h2_max_iext']:.1e}", flush=True)
    return cache


def plan_keys():
    KEEP_RAW.update({job_key("R1", "OW"), job_key("R1", "RD", h=0.0), job_key("G1", "OW")})
    K = []
    for tw in ("R1", "G1", "G0"):
        K.append(job_key(tw, "OW"))
        K.append(job_key(tw, "RD", h=0.0))
        K.append(job_key(tw, "OW", reltol=1e-5)); K.append(job_key(tw, "RD", h=0.0, reltol=1e-5))
    for h in RD_GRID[1:]:
        for tw in ("R1", "G1"):
            K.append(job_key(tw, "RD", h=h))
    for tr in T_RECS:
        for h in HOLDS:
            for p in PARITY:
                for tw in ("R1", "G1"):
                    K.append(job_key(tw, "SR", h=round(h * p, 6), t_rec=tr))
    for tw in ("R2", "G1m"):                                  # Q4 motor in (R_COIL 40 ohm), H6
        for model, h in (("OW", None), ("RD", 0.0)):
            for rt in (None, 1e-5):
                K.append(job_key(tw, model, h=h, motor=True, reltol=rt))
    return K


LOOP_R = a1.R_LX + a1.GAP_RON                    # harness loop R: Lx ESR 20 + gap RON 2 = 22 ohm
F_REC_MODEL = irc.integrate(a1.CX_MAX_PF * 1e-12, 2640e-9, 5e3, a1.LX_DRAWN, LOOP_R)["f_rec"]


def deltas(C):
    """delta_z, delta_eta = max(0.005, 3 x change between reltol 1e-4 and 1e-5) over the twins."""
    dz, de = [], []
    for tw in ("R1", "G1", "G0"):
        for model, h in (("OW", None), ("RD", 0.0)):
            a = C.get(job_key(tw, model, h=h)); b = C.get(job_key(tw, model, h=h, reltol=1e-5))
            if a and b:
                dz.append(abs(a["z"] - b["z"])); de.append(abs(a["eta"] - b["eta"]))
    return max(0.005, 3 * max(dz or [0])), max(0.005, 3 * max(de or [0]))


def classify(R, G, G0, dz, de):
    f_rec = (R["eta"] - G["eta"]) / G["T_load"] if G["T_load"] > 0 else float("nan")
    Dz, De = R["z"] - G["z"], R["eta"] - G["eta"]
    if R["z"] < G["z"] - dz or R["z"] <= 1:
        v = "PUMP-BREAKS"
    elif f_rec >= 0.95 * F_REC_MODEL and R["z"] > G["z"] + dz:
        v = "SINK-REALIZED"
    elif R["eta"] > G0["eta"] + de:
        v = "SINK-PARTIAL"
    elif G["eta"] + de < R["eta"] <= G0["eta"] + de:
        v = "SINK-SUBTHRESHOLD"
    elif abs(De) <= de and abs(Dz) <= dz:
        v = "SINK-IS-PUMP"
    else:
        v = "OUT-OF-SET"
    return dict(verdict=v, dz=Dz, deta=De, f_rec=f_rec, z_R=R["z"], z_G=G["z"], eta_R=R["eta"],
                eta_G=G["eta"], eta_G0=G0["eta"])


GAIN = ("SINK-REALIZED", "SINK-PARTIAL", "SINK-SUBTHRESHOLD")


def grade(C):
    dz, de = deltas(C)
    g = lambda tw, m, h=None, tr=None, **kw: C.get(job_key(tw, m, h=h, t_rec=tr, **kw))
    out = dict(dz=dz, de=de, f_rec_model=F_REC_MODEL)
    out["OW"] = classify(g("R1", "OW"), g("G1", "OW"), g("G0", "OW"), dz, de)
    out["RD"] = {h: classify(g("R1", "RD", h), g("G1", "RD", h), g("G0", "RD", 0.0), dz, de)
                 for h in RD_GRID if g("R1", "RD", h) and g("G1", "RD", h)}
    sr = {}
    for tr in T_RECS:
        for h in HOLDS:
            pts = []
            for p in PARITY:
                hh = round(h * p, 6)
                R, G = g("R1", "SR", hh, tr), g("G1", "SR", hh, tr)
                if R and G:
                    pts.append(classify(R, G, g("G0", "RD", 0.0), dz, de))
            if len(pts) == 3:
                signs = {np.sign(x["deta"]) if abs(x["deta"]) > de else 0 for x in pts}
                mean_de = float(np.mean([x["deta"] for x in pts]))
                gains = [x["verdict"] in GAIN for x in pts]
                cls = pts[1]["verdict"]
                if any(gains) and (len(signs) > 1):
                    cls = "PARITY-ONLY"
                sr[(tr, h)] = dict(points=pts, mean_deta=mean_de, cls=cls,
                                   survives=all(gains) and len(signs) == 1)
    out["SR"] = sr
    ow_gain = out["OW"]["verdict"] in GAIN
    rd_gain = any(v["verdict"] in GAIN for v in out["RD"].values())
    sr_surv = [k for k, v in sr.items() if v["survives"]]
    if sr_surv:
        X = max(k[0] for k in sr_surv)
        final = f"CONDITIONAL-ON-RECOVERY (t_rec <= {X * 1e6:g} us)"
    elif ow_gain and not rd_gain:
        final = "REVERSAL-ONLY (load gap)"
    else:
        final = "OUT-OF-SET"
    out["final"] = final; out["rd_gain"] = rd_gain; out["ow_gain"] = ow_gain
    return out


def q6_spec(res_ow, V_rail=15e3, V_strike=a1.__dict__.get("V_STRIKE", 20e3), margin=1.25):
    """Q6: rectifier spec from the M-OW (Q1) traces only. Scale-free traces are scaled so that the
    rail peak |V1| in the event's cycle = V_rail (the 15 kV operating point)."""
    d = res_ow["d"]; t = d["time"]; rows = trv_record(res_ow)
    trv = max(abs(r["trv_ratio"]) for r in rows)
    dly = min(r["trv_delay_us"] for r in rows)
    cur = []
    for g in LOAD:
        for c in (8, 9, 10):
            t0, t1 = windows_abs(g, c + 1)[c]
            s1 = a1._seg(t, c * T, (c + 1) * T)
            scale = V_rail / float(np.max(np.abs(d["v(1)"][s1])))
            s = a1._seg(t, t0, t1); ii = d[f"i(v_s{g.lower()})"][s] * scale
            cur.append(dict(gap=g, cycle=c, i_pk_A=float(np.max(np.abs(ii))),
                            q_C=float(a1._trap(np.clip(ii, 0, None), t[s])),
                            i2t=float(a1._trap(ii ** 2, t[s]))))
    ipk = max(x["i_pk_A"] for x in cur)
    i2t = max(x["i2t"] for x in cur)
    rms = math.sqrt(i2t / T)                      # one load event per gap per 300 Hz cycle
    return dict(trv_ratio_max=trv, trv_delay_us_min=dly,
                reverse_withstand_kV=trv * V_strike / 1e3,
                reverse_withstand_spec_kV=trv * V_strike * margin / 1e3, margin=margin,
                block_within_us=dly, i_pk_A=ipk, i2t_A2s=i2t, i_rms_A=rms,
                per_event=cur,
                note="[IR] a vacuum rectifier has no reverse-recovery charge -> blocks the TRV "
                     "from the zero; the period-true fit for the ~0.4 us TRV")


# ======================================================================================
# 6. M-SR CHAIN ENGINE — resolves one load event's whole extinction / re-ignition chain
#    exactly (piecewise-LTI, frozen C, event-exact switching) from the ngspice pre-state [ME]
# ======================================================================================
from scipy.linalg import expm as _expm

H_STEP = 5e-9              # expm step (ring 1.38 us, stray modes ~0.3 us periods)            [ME]
N_RAMP = 25                # piecewise-constant sub-steps across the 0.5 us arming ramp          [ME]


def mode_at(segs, t):
    m = None
    for a, b, mm, e in segs:
        if a <= t < b:
            m = mm
    return m


class ChainEngine:
    def __init__(self, res, t0):
        d, m, cfg = res["d"], res["meta"], res["cfg"]
        self.nodes = m["nodes"]; self.ix = {n: k for k, n in enumerate(self.nodes)}; N = len(self.nodes)
        K = np.zeros((N, N))
        def addc(a, b, C):
            ia, ib = self.ix.get(a), self.ix.get(b)
            if ia is not None: K[ia, ia] += C
            if ib is not None: K[ib, ib] += C
            if ia is not None and ib is not None: K[ia, ib] -= C; K[ib, ia] -= C
        for nm, a, b, C in m["caps"]:
            addc(a, b, C)
        for nm, a, b, kind in m["varcaps"]:
            addc(a, b, float(a1._c_of_t(kind, np.array([t0]))[0]))
        self.K = K; self.Ki = np.linalg.inv(K); self.N = N
        self.inds = [x for x in m["inds"] if x[3] > 0]
        Rm = dict(m.get("motor_r", []))
        self.R = np.array([cfg.rlx if nm in ("Lx3", "Lx4") else Rm.get(nm, 0.0) for nm, a, b, L in self.inds])
        self.L = np.array([x[3] for x in self.inds])
        self.gaps = m["gaps"]
        Bg = np.zeros((N, len(self.gaps))); Bl = np.zeros((N, len(self.inds)))
        for k, (g, a, b) in enumerate(self.gaps):
            if a in self.ix: Bg[self.ix[a], k] += 1
            if b in self.ix: Bg[self.ix[b], k] -= 1
        for k, (nm, a, b, L) in enumerate(self.inds):
            if a in self.ix: Bl[self.ix[a], k] += 1
            if b in self.ix: Bl[self.ix[b], k] -= 1
        self.Bg, self.Bl = Bg, Bl
        t = d["time"]
        V0 = np.array([np.interp(t0, t, d[f"v({n})"]) for n in self.nodes])
        I0 = np.array([np.interp(t0, t, d[f"i(l_{nm.lower()})"]) for nm, a, b, L in self.inds])
        self.x0 = np.concatenate([V0, I0])
        self._cache = {}

    def A(self, gvec):
        key = tuple(np.round(gvec, 12))
        if key not in self._cache:
            N, m = self.N, len(self.inds)
            A = np.zeros((N + m, N + m))
            A[:N, :N] = -self.Ki @ (self.Bg @ np.diag(gvec) @ self.Bg.T)
            A[:N, N:] = -self.Ki @ self.Bl
            A[N:, :N] = (self.Bl.T) / self.L[:, None]
            A[N:, N:] = -np.diag(self.R / self.L)
            self._cache[key] = (A, {})
        return self._cache[key]

    def step(self, gvec, x, h):
        A, E = self.A(gvec)
        hk = round(h, 15)
        if hk not in E:
            E[hk] = _expm(A * h)
        return E[hk] @ x

    def vgap(self, x, k):
        return float(self.Bg[:, k] @ x[:self.N])


def resolve_chain(res, sched, g, t_ign, t_end, model, h, t_rec, holdoff=HOLDOFF, span=None):
    """Run the M-SR (or M-RD) state machine for load gap g from t_ign with other gaps held at their
    scheduled modes. Returns (segments for g on [t_ign, t_end], event records)."""
    E = ChainEngine(res, t_ign)
    kg = [x[0] for x in E.gaps].index(g)
    RON, ROFF = a1.GAP_RON, a1.GAP_ROFF
    others = {k: mode_at(sched[x[0]], t_ign + 1e-9) for k, x in enumerate(E.gaps) if k != kg}
    x = E.x0.copy(); t = t_ign
    segs = []; recs = []
    state = "arc"; Vf = E.vgap(x, kg); p1 = None; pk = 0.0; tpk = t; hsgn = 0.0
    ev = dict(t_ign=t_ign, Vf=Vf, p1=None, ext=None, reignite=None, trv=None)
    seg_start, seg_edge = t_ign, EDGE_IGN
    t_ext = None; t_h_end = None; trv_pk = 0.0
    tstop = t_end if span is None else min(t_end, t_ign + span)
    closing = False                 # window end while arcing: extinguish at the NEXT current zero
    ramp_end = t_ign + EDGE_IGN

    def gvec_at(xx, tt):
        gv = np.full(len(E.gaps), 1.0 / ROFF)
        for k, mm in others.items():
            v = E.vgap(xx, k)
            if mm == "bi" or (mm == "f" and v > 0) or (mm == "r" and v < 0):
                gv[k] = 1.0 / RON
        if state == "arc":
            frac = 1.0 if tt >= ramp_end else max(0.0, (tt - t_ign) / EDGE_IGN)
            gv[kg] = max(1.0 / ROFF, frac / RON)
        return gv
    first = True
    while t < tstop or closing:
        if state == "arc" and t < ramp_end:
            hh = min(EDGE_IGN / N_RAMP, ramp_end - t)
            gv = gvec_at(x, t + 0.5 * hh)
        else:
            hh = H_STEP if closing else min(H_STEP, tstop - t)
            gv = gvec_at(x, t)
        x1 = E.step(gv, x, hh)
        v0, v1 = E.vgap(x, kg), E.vgap(x1, kg)
        # other rectifiers changing conduction inside the step -> bisect to the sign change
        def other_flip(xa, xb):
            for k, mm in others.items():
                if mm in ("f", "r") and np.sign(E.vgap(xa, k)) != np.sign(E.vgap(xb, k)):
                    return True
            return False
        trig = other_flip(x, x1)
        if state == "arc":
            i0, i1 = v0 * gv[kg], v1 * gv[kg]
            zero = (not first) and np.sign(v0) != np.sign(v1) and v0 != 0
            trig = trig or zero
        elif state == "hold":
            rho = lambda tt: 1.0 if t_rec <= 0 else 1.0 - math.exp(-(tt - t_ext) / t_rec)
            thr1 = abs(v1) - rho(t + hh) * abs(Vf)
            re = (t + hh > t_ext + 2 * EDGE_SW) and thr1 > 0
            trig = trig or re or (t + hh >= t_h_end)
        if trig:
            lo, hi = 0.0, hh
            for _ in range(50):
                mid = 0.5 * (lo + hi); xm = E.step(gv, x, mid); vm = E.vgap(xm, kg)
                c = other_flip(x, xm)
                if state == "arc":
                    c = c or (np.sign(v0) != np.sign(vm) and v0 != 0 and not first)
                elif state == "hold":
                    c = c or ((t + mid > t_ext + 2 * EDGE_SW) and abs(vm) - rho(t + mid) * abs(Vf) > 0) \
                        or (t + mid >= t_h_end)
                if c:
                    hi = mid
                else:
                    lo = mid
            hh = hi; x1 = E.step(gv, x, hh); v1 = E.vgap(x1, kg)
        tn = t + hh
        if state == "arc":
            iabs = abs(v1) * gv[kg]                          # actual (ramped) conductance
            ev["p1_full"] = max(ev.get("p1_full") or 0.0, iabs) if p1 is None else ev.get("p1_full")
            if p1 is None and tn < seg_start + T_SPIKE:
                iabs = 0.0                                   # stray-dump spike excluded (T_SPIKE)
            if iabs > pk:
                pk, tpk, hsgn = iabs, tn, np.sign(v1)
            first = False
            if closing and trig and np.sign(v0) != np.sign(v1) and v0 != 0:
                segs.append((t_end, tn, "f" if np.sign(v0) > 0 else "r", EDGE_SW))
                ev["ext"] = tn; ev["i_at_ext"] = 0.0; ev["window_end"] = True
                recs.append(ev); return segs, recs
            if trig and np.sign(v0) != np.sign(v1) and v0 != 0 and not closing:
                # a half-cycle closed at tn with peak pk and sign hsgn
                if p1 is None:
                    p1 = pk; ev["p1"] = p1
                if pk < h * p1:
                    mode_x = "f" if hsgn > 0 else "r"
                    # hand-off bi -> rectifier inside the same-sign half-cycle, never inside the
                    # arming ramp (it would cut the ramp short); seamless by construction
                    tsw = min(max(tpk, ramp_end + EDGE_SW), tn - 2 * EDGE_SW)
                    segs.append((seg_start, tsw, "bi", seg_edge))
                    segs.append((tsw, tn, mode_x, EDGE_SW))
                    tpk = tsw
                    ev.update(ext=tn, sgn_ext=hsgn, i_at_ext=0.0)
                    t_ext = tn
                    if model == "RD" or holdoff <= 0:
                        if mode_x == "f":
                            segs[-1] = (tpk, t_end, "f", EDGE_SW)
                        else:
                            segs.append((tn, t_end, "f", EDGE_SW))
                        recs.append(ev); return segs, recs
                    state = "hold"; t_h_end = min(t_ext + holdoff, t_end); trv_pk = 0.0
                    seg_start = tn
                pk = 0.0
        elif state == "hold":
            trv_pk = max(trv_pk, abs(v1))
            if tn >= t_h_end - 1e-15:
                segs.append((seg_start, t_h_end, "off", EDGE_SW))
                ev.update(reignite=None, trv=trv_pk / abs(Vf))
                recs.append(ev)
                if t_h_end < t_end:
                    segs.append((t_h_end, t_end, "f", EDGE_SW))
                return segs, recs
            if trig and (tn > t_ext + 2 * EDGE_SW) and abs(v1) - rho(tn) * abs(Vf) >= -1e-9 * abs(Vf):
                segs.append((seg_start, tn, "off", EDGE_SW))
                ev.update(reignite=tn, trv=trv_pk / abs(Vf)); recs.append(ev)
                state = "arc"; Vf = v1; p1 = None; pk = 0.0; first = True
                ev = dict(t_ign=tn, Vf=Vf, p1=None, ext=None, reignite=None, trv=None)
                seg_start, seg_edge = tn, EDGE_SW; ramp_end = tn   # re-ignition: no arming ramp
        x, t = x1, tn
        if state == "arc" and not closing and t >= tstop and span is None:
            # the window closes on a live arc: the electrodes part, the arc goes out at its next
            # natural current zero (rectifier of the current's sign from t_end) -> no chop (H2)
            segs.append((seg_start, t_end, "bi", seg_edge)); closing = True
            if t - t_ign > 3e-3:
                break
    if closing:
        recs.append(ev); return segs, recs
    # span reached while arcing or holding
    if state == "arc":
        segs.append((seg_start, t_end, "bi", seg_edge)); ev["i_at_end"] = abs(E.vgap(x, kg)) / RON
    else:
        segs.append((seg_start, t_end, "off", EDGE_SW))
    recs.append(ev)
    return segs, recs


def fixed_point_sr(cfg, model, h, t_rec, holdoff=HOLDOFF, maxit=6, tol_ns=30):
    """Machine-level fixed point with the chain engine resolving each load event."""
    sched = sched_static(cfg, "f")
    for it in range(maxit):
        cfg.name = re.sub(r"_it\d+$", "", cfg.name) + f"_it{it}"
        r = run(cfg, sched)
        new = dict(sched); events = {}
        tend = r["d"]["time"][-1]
        for g in LOAD:
            segs = []; recs = []
            for (t0, t1) in windows_abs(g, cfg.ncyc):
                if t0 >= tend:
                    break
                s_, r_ = resolve_chain(r, sched, g, t0, t1, model, h, t_rec, holdoff)
                segs += s_; recs += r_
            new[g] = segs; events[g] = recs
        same = _close(new, sched, tol_ns)
        if same:
            r["iters"] = it + 1; r["events"] = events; r["converged"] = True
            return r
        _rm_raw(cfg.name) if it < maxit - 1 else None
        sched = new
    r["iters"] = maxit; r["events"] = events; r["converged"] = False
    return r


# ======================================================================================
# 7. REPORT
# ======================================================================================
def report(C=None):
    import json
    C = C if C is not None else json.load(open(CACHE))
    G = grade(C)
    cols = ["key", "twin", "model", "h", "t_rec", "stray", "motor", "reltol", "cycles", "iters",
            "converged", "z", "eta", "resid", "resid_gap", "trip_shift", "T_load", "T_esr", "T_motor",
            "n_events", "n_reignite", "h2_max_iext", "error"]
    with open(os.path.join(ROOT, "island_gapbracket_runs.csv"), "w", newline="") as f:
        w = csv.writer(f); w.writerow(cols)
        for k, v in C.items():
            w.writerow([v.get(c) if not isinstance(v.get(c), float) else f"{v.get(c):.6g}" for c in cols])
    with open(os.path.join(ROOT, "island_gapbracket_trv.csv"), "w", newline="") as f:
        w = csv.writer(f); w.writerow(["key", "gap", "cycle", "Vf", "t_ext_us", "i_ext_over_p1",
                                       "trv_ratio", "trv_delay_us"])
        for k, v in C.items():
            if isinstance(v.get("trv"), list):
                for r in v["trv"]:
                    w.writerow([k] + [r.get(c) for c in ("gap", "cycle", "Vf", "t_ext_us", "i_ext_over_p1",
                                                          "trv_ratio", "trv_delay_us")])
    try:
        _plot(C, G)
    except Exception as e:
        print("plot skipped:", e)
    Gs = dict(G); Gs["SR"] = {f"trec={k[0]:g}|h={k[1]:g}": v for k, v in G["SR"].items()}
    json.dump(Gs, open(os.path.join(HERE, ".ia2_grade.json"), "w"), default=str, indent=1)
    return G


def _plot(C, G):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.4))
    # Q2
    hs = [h for h in RD_GRID if h in G["RD"]]
    ax[0].plot([max(h, 1e-4) for h in hs], [G["RD"][h]["deta"] for h in hs], "o-", label="M-RD  Δη (R1−G1)")
    ax[0].axhline(G["OW"]["deta"], color="#e76f51", ls="--", label="M-OW bound")
    ax[0].axhline(0, color="k", lw=.6); ax[0].set_xscale("log")
    ax[0].set_xlabel("I_hold / i_pk1 (leftmost = →0)"); ax[0].set_ylabel("Δη"); ax[0].legend(fontsize=7)
    ax[0].set_title("Q2 ring-down")
    # Q3 heat map of parity-averaged Δη
    M = np.full((len(T_RECS), len(HOLDS)), np.nan)
    for i, tr in enumerate(T_RECS):
        for j, h in enumerate(HOLDS):
            v = G["SR"].get((tr, h))
            if v:
                M[i, j] = v["mean_deta"]
    im = ax[1].imshow(M, cmap="RdBu", vmin=-0.2, vmax=0.2, aspect="auto")
    ax[1].set_xticks(range(len(HOLDS))); ax[1].set_xticklabels(HOLDS)
    ax[1].set_yticks(range(len(T_RECS))); ax[1].set_yticklabels([f"{t*1e6:g}" for t in T_RECS])
    ax[1].set_xlabel("I_hold / i_pk1"); ax[1].set_ylabel("t_rec (us)")
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if not np.isnan(M[i, j]):
                cls = G["SR"][(T_RECS[i], HOLDS[j])]["cls"]
                ax[1].text(j, i, f"{M[i, j]:+.3f}\n{cls.replace('SINK-', '')}", ha="center", va="center", fontsize=6)
    fig.colorbar(im, ax=ax[1]); ax[1].set_title("Q3 M-SR parity-averaged Δη")
    # TRV on the one-way bound
    k = job_key("R1", "OW")
    if isinstance(C.get(k, {}).get("trv"), list):
        tr = C[k]["trv"]
        ax[2].bar(range(len(tr)), [abs(r["trv_ratio"]) for r in tr], color="#2a9d8f")
        ax[2].axhline(1.0, color="k", ls=":", label="|V| = V_f (a gap that fired at V_f)")
        ax[2].set_xticks(range(len(tr))); ax[2].set_xticklabels([f"{r['gap']}\nc{r['cycle']}" for r in tr], fontsize=6)
        ax[2].set_ylabel("reverse |V_gap| peak / V_f"); ax[2].legend(fontsize=7)
        ax[2].set_title("H4 TRV after the first zero (M-OW)")
    fig.suptitle(f"ISLAND-ASDRAWN Pass A' — final grade: {G['final']}", fontsize=11)
    fig.tight_layout(); fig.savefig(os.path.join(ROOT, "island_gapbracket.png"), dpi=110); plt.close(fig)


def admissibility(res, cycles=(8, 9, 10)):
    """Largest |V_gap| the load gap BLOCKS (outside its conducting intervals) after its first
    extinction, over the rest of its window, / |V_f| of the event that preceded it. A symmetric
    self-break gap can hold at most |V_f| (rho_max = 1); > 1 means the model relied on a rectifier."""
    d = res["d"]; t = d["time"]; out = []
    for g in LOAD:
        a, b = _gap_nodes(g)
        v = (d[f"v({a})"] if a != "0" else 0 * t) - (d[f"v({b})"] if b != "0" else 0 * t)
        segs = res["sched"][g]
        for c in cycles:
            t0, t1 = windows_abs(g, c + 1)[c]
            k0, k1 = np.searchsorted(t, t0), np.searchsorted(t, t1)
            tt, vv = t[k0:k1], v[k0:k1]
            cond = np.zeros(len(tt), bool)
            for s0, s1, m, e in segs:
                if m == "bi" and s1 > t0 and s0 < t1:
                    cond |= (tt >= s0) & (tt <= s1 + EDGE_SW)
                if m in ("f", "r") and s1 > t0 and s0 < t1:
                    sgn = 1 if m == "f" else -1
                    cond |= (tt >= s0) & (tt <= s1) & (sgn * vv > 0)
            Vf = float(np.interp(t0, t, v))
            first_off = np.where(~cond & (tt > t0 + 0.2e-6))[0]
            if not len(first_off):
                out.append(dict(gap=g, cycle=c, blocked_over_Vf=0.0)); continue
            kb = first_off
            j = kb[int(np.argmax(np.abs(vv[kb])))]
            out.append(dict(gap=g, cycle=c, blocked_over_Vf=float(abs(vv[j]) / abs(Vf)),
                            polarity=("reverse" if np.sign(vv[j]) != np.sign(Vf) else "forward"),
                            at_us=float((tt[j] - t0) * 1e6)))
    return out


def admissibility_events(res, cycles=(8, 9, 10)):
    """Per holdoff ('off' segment) of the load gap: max |V_gap| / |V_f| of the event that preceded
    it (the M-SR rule's own reference), plus the reverse |V| held by the post-holdoff forward
    rectifier / that V_f. rho_max = 1: a value > 1 would be a rectifier."""
    d = res["d"]; t = d["time"]; out = []
    for g in LOAD:
        a, b = _gap_nodes(g)
        v = (d[f"v({a})"] if a != "0" else 0 * t) - (d[f"v({b})"] if b != "0" else 0 * t)
        segs = sorted(res["sched"][g])
        for c in cycles:
            t0, t1 = windows_abs(g, c + 1)[c]
            Vf = None; worst_off = 0.0; worst_rect = 0.0
            for s0, s1, m, e in segs:
                if s1 < t0 or s0 > t1:
                    continue
                if m == "bi":
                    Vf = float(np.interp(s0, t, v))
                k0, k1 = np.searchsorted(t, s0 + 2 * EDGE_SW), np.searchsorted(t, s1)
                if k1 <= k0 or Vf is None:
                    continue
                seg = v[k0:k1]
                if m == "off":
                    worst_off = max(worst_off, float(np.max(np.abs(seg)) / abs(Vf)))
                if m == "f":
                    worst_rect = max(worst_rect, float(np.max(np.clip(-seg, 0, None)) / abs(Vf)))
            out.append(dict(gap=g, cycle=c, holdoff_max_over_Vf_event=worst_off,
                            rect_reverse_over_Vf_event=worst_rect))
    return out
